#! /bin/sh

# Build OCI container image with almost all packages suitable for jails,
# excluding toolchain.

OCI_BASE_IMAGE=runtime

oci_image_build() {
	set_cmd ${workdir} /bin/sh
	install_packages ${abi} ${workdir} \
		HardenedBSD-bmake \
		HardenedBSD-dma \
		HardenedBSD-inetd \
		HardenedBSD-ipf \
		HardenedBSD-ipfw \
		HardenedBSD-natd \
		HardenedBSD-netmap \
		HardenedBSD-pf \
		HardenedBSD-ssh \
		HardenedBSD-telnet \
		HardenedBSD-xz \
		HardenedBSD-zfs \
		HardenedBSD-set-minimal-jail
}

